[package]
name = "shopping_list_parser"
version = "0.1.4"
edition = "2021"
description = "Shopping-list parser for edu purposes"
license = "MIT"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
pest = "2.7.14"
pest_derive = "2.7.14"
thiserror = "2.0.3"
